version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: monthly
    labels:
      - dependencies
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    labels:
      - dependencies
