[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "cloudb"
version = "1.0.9"
description = "A cli to synchronize the internal sgid with the open sgid"
readme = "src/readme.md"
license = { text = "MIT" }
authors = [{ name = "UGRC", email = "ugrc-developers@utah.gov" }]
keywords = ["gis"]
classifiers = [
  "Development Status :: 5 - Production/Stable",
  "Intended Audience :: Developers",
  "Topic :: Utilities",
]
dependencies = [
  "colorama==0.*",
  "docopt==0.*",
  "pyodbc==5.*",
  "psycopg2-binary==2.*",
  "python-dotenv==1.*",
  "gdal==3.*",
]

[project.urls]
Homepage = "https://github.com/agrc/open-sgid"
"Issue Tracker" = "https://github.com/agrc/open-sgid/issues"

[project.optional-dependencies]
cloud-run = ["google-cloud-storage==3.*"]
dev = [
  "pytest-cov>=6,<8",
  "pytest-instafail==0.5.*",
  "pytest-mock==3.*",
  "pytest-ruff==0.*",
  "pytest-watch==4.*",
  "pytest>=8,<10",
  "pytest-runner",
  "ruff==0.*",
]

[project.scripts]
cloudb = "cloudb.main:main"

[tool.hatch.build.targets.wheel]
packages = ["src/cloudb"]

[tool.ruff]
line-length = 120
[tool.ruff.lint]
ignore = ["E501"]
[tool.black]
line-length = 120
[tool.pytest.ini_options]
minversion = "6.0"
testpaths = ["tests", "src"]
norecursedirs = [".env", "data", "maps", ".github", ".vscode"]
console_output_style = "count"
addopts = "--ruff --cov-branch --cov=cloudb --cov-report term --cov-report xml:cov.xml --instafail"
